### ISSUE TITLE
VLC Open Network Stream Option

### ISSUE THREAD

**Issue by bretmh** [adar2378/mx_player_plugin#1]
Is there any option for this using the VLC player?

**Comment by adar2378** [comment]
I'll try to implement soon :)

**Comment by adar2378** [comment]
Added support for vlc player too. but make sure the usesr have vlc installed on their device.

**Comment by bretmh** [comment]
How do we use this widget?

**Comment by adar2378** [comment]
``
import 'package:mx_player_plugin/mx_player_plugin.dart';

await PlayerPlugin.openWithVlcPlayer(String url);
``

It doesn't have subtitle support with vlc player yet.

**Comment by bretmh** [comment]
Okay, it's just weird because this doesn't return a widget to use for the player.

Do I need another plugin for this for usuage?

**Comment by adar2378** [comment]
https://pub.dev/packages/mx_player_plugin just update to the latest version! I haven't tested yet as I don't have any testing device with me right now. But it should work.

**Comment by adar2378** [comment]
And it will not return any widget. It will simply open that url with VLC player. if you have it installed on your device.

**Comment by adar2378** [comment]
Added vlc player support but the subtitle showing for vlc will not work from the plugin. please view the latest version readme

**Comment by gauravmehta13** [comment]
Is there any way to use both Vlc plugin and mx player plugin simultaneously?
onPressed: () async {
                await PlayerPlugin.openWithMxPlayer(movie, '');
                await PlayerPlugin.openWithVlcPlayer(movie);
              }
like if a person has mx player installed it will open in mx and if another has vlc installed t will automatically open in VLC

**Comment by adar2378** [comment]
You will have to use another package to check if the user has vlc or mx player installed on their phone.
https://pub.dev/packages/flutter_appavailability
Upon the availability open the desired application
