### ISSUE TITLE
Please Sample complete 

### ISSUE THREAD

**Issue by fanfantasi** [adar2378/mx_player_plugin#2]
Please Sample Code Complate open video files using mx player with subtitle, Please Help?.

**Comment by adar2378** [comment]
import 'package:mx_player_plugin/mx_player_plugin.dart';

Then later use this ,

await PlayerPlugin.openWithMxPlayer(String url, String subUrl);

You must provide the http/https url for both. Won't work for offline videos or subtitle files.

**Comment by adar2378** [comment]
closing it since no further comment
