### ISSUE TITLE
Improper sample code provided

### ISSUE THREAD

**Issue by gauravmehta13** [adar2378/mx_player_plugin#3]
I am unable to make it work can u send a proper sample code please

**Comment by adar2378** [comment]
`await PlayerPlugin.openWithMxPlayer(String videoUrl, String subtitleUrl);`
Which part you don't understand?

**Comment by gauravmehta13** [comment]
I am newbie in flutter, don't know where to use this code await "PlayerPlugin.openWithMxPlayer(String videoUrl, String subtitleUrl);"
Also asked  in some flutter grups but in futile.
tried using the sample code provided but still cant figure out where to use openwithMxPlayer!!
It will be a great help to me if you can show me how to use this function with onpressed(){} or onTap(){}

**Comment by adar2378** [comment]
okay, suppose this is your video URL "http://distribution.bbb3d.renderfarming.net/video/mp4/bbb_sunflower_1080p_60fps_normal.mp4"
And you have a button that will trigger opening this video with mxplayer
```Dart
FlatButton(
   onPressed:(){
    await PlayerPlugin.openWithMxPlayer("http://distribution.bbb3d.renderfarming.net/video/mp4/bbb_sunflower_1080p_60fps_normal.mp4");
  }
)
```

**Comment by gauravmehta13** [comment]
Thanks a lot Sir, working fine.
